import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { Config } from "../config.js";
import { scanVault } from "../vault/scanner.js";
import { loadEmbeddings, type EmbeddingStore } from "../embeddings/loader.js";
import { findInsightPairs, type InsightPair } from "../analysis/pairs.js";

function obsidianLink(path: string): string {
  const stem = path.replace(/\.md$/, "").split("/").pop() ?? path;
  return `[[${stem}]]`;
}

export async function runInsights(cfg: Config): Promise<void> {
  const startedAt = new Date();
  console.log(`[insights] scanning vault at ${cfg.vault.path} ...`);
  const index = await scanVault({
    vaultPath: cfg.vault.path,
    ignoredFolders: cfg.vault.ignored_folders,
  });
  console.log(`[insights] scanned ${index.notes.size} notes`);

  const store = await loadEmbeddings({
    embeddingsDir: cfg.vault.embeddings_dir!,
    knownPaths: index.notes.keys(),
  });
  console.log(
    `[insights] loaded ${store.numNotes} embedded notes / ${store.numChunks} chunks`,
  );

  const { pairs, queriesRun } = await findInsightPairs(index, store, {
    topK: cfg.insights.top_k,
    minSimilarity: cfg.insights.min_similarity,
    minGraphDistance: cfg.insights.min_graph_distance,
  });
  const capped = pairs.slice(0, cfg.insights.max_per_report);
  console.log(
    `[insights] ran ${queriesRun} vector queries; found ${pairs.length} candidate pairs, keeping top ${capped.length}`,
  );

  const report = renderReport(capped, {
    generatedAt: startedAt,
    totalNotes: index.notes.size,
    queriesRun,
    candidatePairs: pairs.length,
    store,
  });

  await mkdir(cfg.inbox.dir, { recursive: true });
  const dateStamp = startedAt.toISOString().slice(0, 10);
  const outPath = join(cfg.inbox.dir, `daily-insights-${dateStamp}.md`);
  await writeFile(outPath, report, "utf-8");
  console.log(`[insights] wrote ${outPath}`);
}

function renderReport(
  insights: InsightPair[],
  ctx: {
    generatedAt: Date;
    totalNotes: number;
    queriesRun: number;
    candidatePairs: number;
    store: EmbeddingStore;
  },
): string {
  const lines: string[] = [];
  const iso = ctx.generatedAt.toISOString();
  lines.push(`# Daily Insights — ${iso.slice(0, 10)}`);
  lines.push("");
  lines.push(`> Generated by vault-sidekick at ${iso}.`);
  lines.push(
    `> Scanned ${ctx.totalNotes} notes · ${ctx.store.numChunks} chunks across ${ctx.store.numNotes} embedded notes · ran ${ctx.queriesRun} vector queries.`,
  );
  if (ctx.store.missingPaths.length > 0) {
    lines.push(
      `> ${ctx.store.missingPaths.length} notes have no embedding yet (open Obsidian to refresh).`,
    );
  }
  lines.push("");
  lines.push("## Surprising connections");
  lines.push("");
  lines.push(
    "Pairs that are semantically close but distant in your link graph. Consider whether they should be linked.",
  );
  lines.push("");
  lines.push(
    "Confidence tags: **EXTRACTED** = strong signal · **INFERRED** = worth a look · **AMBIGUOUS** = borderline.",
  );
  lines.push("");

  if (insights.length === 0) {
    lines.push(
      "_No surprising connections above thresholds. Adjust `insights.min_similarity` or `insights.min_graph_distance` in your config to widen the net._",
    );
    lines.push("");
    return lines.join("\n");
  }

  for (let i = 0; i < insights.length; i++) {
    const x = insights[i]!;
    const distLabel = x.graphDistance === Infinity ? "no path" : `${x.graphDistance} hops`;
    lines.push(
      `### ${i + 1}. ${obsidianLink(x.sourcePath)} ↔ ${obsidianLink(x.neighbourPath)}`,
    );
    lines.push("");
    lines.push(
      `**sim** ${x.similarity.toFixed(3)} · **graph** ${distLabel} · **${x.confidence}**`,
    );
    lines.push("");
    lines.push(`> from \`${x.sourcePath}\`: ${x.sourceExcerpt}`);
    lines.push("");
    lines.push(`> from \`${x.neighbourPath}\`: ${x.neighbourExcerpt}`);
    lines.push("");
  }

  return lines.join("\n");
}
